This notebook is for concatenating all of the relative risk data into a single dataset.

In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
def standardize_column_names(df, keep_length_of_stay=False):
    if "Unnamed: 0" in df.columns:
        df.drop(columns=["Unnamed: 0"], inplace=True)
    if "del_start" in df.columns:
        df.drop(columns=["del_start"], inplace=True)
    if "start" in df.columns:
        df.drop(columns=["start"], inplace=True)
    if "end" in df.columns:
        df.rename(columns={"end" :"LOS"}, inplace=True)
    if "index" in df.columns:
        df.drop(columns=["index"], inplace=True)
    if "patientunitstayid" in df.columns:
        df.rename(columns={"patientunitstayid": "PatientStayID"}, inplace=True)
    if "delirium?" in df.columns:
        df.rename(columns={"delirium?" : "Class"}, inplace=True)
    df.replace(to_replace=[True, False], value=[1, 0], inplace=True)
    if keep_length_of_stay is False:
        df.drop(columns=["Class", "LOS"], inplace=True)
    return df

In [3]:
lead = 0
window = 1

In [4]:
if os.path.isfile("../csv/relative_{}hr_lead_{}hr_obs_data/relative_{}hr_lead_{}hr_obs_data_set.csv".format(lead, window, lead, window)):
    df = standardize_column_names(pd.read_csv("../csv/relative_{}hr_lead_{}hr_obs_data/relative_{}hr_lead_{}hr_obs_data_set.csv".format(lead, window, lead, window)), keep_length_of_stay=True)
    df.to_csv("../csv/relative_{}hr_lead_{}hr_obs_data/relative_{}hr_lead_{}hr_obs_patientstayid_list.csv".format(lead, window, lead, window),index=False)

# Reformatting Files

In [5]:
list_of_files = [
    "data_set",
    "AKI_feature",
    "AllDrugFeatures",
    "comorbidity", 
    "GCS_feature",
    "lab_feature_data",
    "rass_feature",
    "SOFA_features",
    "temp_feature",
    "vent_feature",
    "sepsis_feature",
    "intakeoutput",
    "dialysis",
    "surgical",
    "MV_duration"
]

print("Files Unedited")

# PatientStayID List
if os.path.isfile("../csv/relative_{}hr_lead_{}hr_obs_data/relative_{}hr_lead_{}hr_obs_data_set.csv".format(lead, window, lead, window)):
    df = pd.read_csv("../csv/relative_{}hr_lead_{}hr_obs_data/relative_{}hr_lead_{}hr_obs_data_set.csv".format(lead, window, lead, window))
    df = standardize_column_names(df, keep_length_of_stay=True)
    df.to_csv("../csv/relative_{}hr_lead_{}hr_obs_data/relative_{}hr_lead_{}hr_obs_patientstayid_list.csv".format(lead, window, lead, window),index=False)
else:
    print("data_set")

# AKI
if os.path.isfile("../csv/relative_{}hr_lead_{}hr_obs_data/relative_{}hr_lead_{}hr_obs_AKI_feature.csv".format(lead, window, lead, window)):
    df = pd.read_csv("../csv/relative_{}hr_lead_{}hr_obs_data/relative_{}hr_lead_{}hr_obs_AKI_feature.csv".format(lead, window, lead, window))
    df = standardize_column_names(df)
    df.to_csv("../csv/relative_{}hr_lead_{}hr_obs_data/relative_{}hr_lead_{}hr_obs_aki.csv".format(lead, window, lead, window),index=False)
    os.remove("../csv/relative_{}hr_lead_{}hr_obs_data/relative_{}hr_lead_{}hr_obs_AKI_feature.csv".format(lead, window, lead, window))
else:
    print("AKI_feature")

# Drug
if os.path.isfile("../csv/relative_{}hr_lead_{}hr_obs_data/relative_{}hr_lead_{}hr_obs_AllDrugFeatures.csv".format(lead, window, lead, window)):
    df = pd.read_csv("../csv/relative_{}hr_lead_{}hr_obs_data/relative_{}hr_lead_{}hr_obs_AllDrugFeatures.csv".format(lead, window, lead, window))
    df = standardize_column_names(df)
    df.to_csv("../csv/relative_{}hr_lead_{}hr_obs_data/relative_{}hr_lead_{}hr_obs_drug.csv".format(lead, window, lead, window),index=False)
    os.remove("../csv/relative_{}hr_lead_{}hr_obs_data/relative_{}hr_lead_{}hr_obs_AllDrugFeatures.csv".format(lead, window, lead, window))
else:
    print("AllDrugFeatures")

# Comorbidity
if os.path.isfile("../csv/relative_{}hr_lead_{}hr_obs_data/relative_{}hr_lead_{}hr_obs_comorbidity.csv".format(lead, window, lead, window)):
    df = pd.read_csv("../csv/relative_{}hr_lead_{}hr_obs_data/relative_{}hr_lead_{}hr_obs_comorbidity.csv".format(lead, window, lead, window))
    df = standardize_column_names(df)
    if "comorbidity" not in df.columns[10]:
        df = df.iloc[:, :32]
        df.drop(["psycho"], axis=1, inplace=True)
        df = df.add_prefix("comorbidity_")
        df.rename(columns={"comorbidity_PatientStayID" : "PatientStayID"}, inplace=True)
    df.to_csv("../csv/relative_{}hr_lead_{}hr_obs_data/relative_{}hr_lead_{}hr_obs_comorbidity.csv".format(lead, window, lead, window),index=False)
else:
    print("comorbidity")


# GCS
if os.path.isfile("../csv/relative_{}hr_lead_{}hr_obs_data/relative_{}hr_lead_{}hr_obs_GCS_feature.csv".format(lead, window, lead, window)):
    df = pd.read_csv("../csv/relative_{}hr_lead_{}hr_obs_data/relative_{}hr_lead_{}hr_obs_GCS_feature.csv".format(lead, window, lead, window))
    df = standardize_column_names(df)
    df.to_csv("../csv/relative_{}hr_lead_{}hr_obs_data/relative_{}hr_lead_{}hr_obs_gcs.csv".format(lead, window, lead, window),index=False)
    os.remove("../csv/relative_{}hr_lead_{}hr_obs_data/relative_{}hr_lead_{}hr_obs_GCS_feature.csv".format(lead, window, lead, window))
else:
    print("GCS_feature")

# Labs
if os.path.isfile("../csv/relative_{}hr_lead_{}hr_obs_data/relative_{}hr_lead_{}hr_obs_lab_feature_data.csv".format(lead, window, lead, window)):
    df = pd.read_csv("../csv/relative_{}hr_lead_{}hr_obs_data/relative_{}hr_lead_{}hr_obs_lab_feature_data.csv".format(lead, window, lead, window))
    df = standardize_column_names(df)
    df.to_csv("../csv/relative_{}hr_lead_{}hr_obs_data/relative_{}hr_lead_{}hr_obs_labs.csv".format(lead, window, lead, window),index=False)
    os.remove("../csv/relative_{}hr_lead_{}hr_obs_data/relative_{}hr_lead_{}hr_obs_lab_feature_data.csv".format(lead, window, lead, window))
else:
    print("lab_feature_data")

# Rass
if os.path.isfile("../csv/relative_{}hr_lead_{}hr_obs_data/relative_{}hr_lead_{}hr_obs_rass_feature.csv".format(lead, window, lead, window)):
    df = pd.read_csv("../csv/relative_{}hr_lead_{}hr_obs_data/relative_{}hr_lead_{}hr_obs_rass_feature.csv".format(lead, window, lead, window))
    df = standardize_column_names(df)
    df.to_csv("../csv/relative_{}hr_lead_{}hr_obs_data/relative_{}hr_lead_{}hr_obs_rass.csv".format(lead, window, lead, window),index=False)
    os.remove("../csv/relative_{}hr_lead_{}hr_obs_data/relative_{}hr_lead_{}hr_obs_rass_feature.csv".format(lead, window, lead, window))
else:
    print("rass_feature")

# SOFA
if os.path.isfile("../csv/relative_{}hr_lead_{}hr_obs_data/relative_{}hr_lead_{}hr_obs_SOFA_features.csv".format(lead, window, lead, window)):
    df = pd.read_csv("../csv/relative_{}hr_lead_{}hr_obs_data/relative_{}hr_lead_{}hr_obs_SOFA_features.csv".format(lead, window, lead, window))
    df = standardize_column_names(df)
    df = df[["PatientStayID", "vasopressors", "ventilator", "sofa_resp", "sofa_nervous", "sofa_cardio", "sofa_liver", "sofa_coag",
                "sofa_kidney", "sofa_score", "qsofa_altered_mental", "qsofa_resp_rate", "qsofa_sys_bp", "qsofa_score", "sepsis_lactate", "sepsis_map"]]
    df.to_csv("../csv/relative_{}hr_lead_{}hr_obs_data/relative_{}hr_lead_{}hr_obs_sofa.csv".format(lead, window, lead, window),index=False)
    os.remove("../csv/relative_{}hr_lead_{}hr_obs_data/relative_{}hr_lead_{}hr_obs_SOFA_features.csv".format(lead, window, lead, window))
else:
    print("SOFA_features")

# Temp
if os.path.isfile("../csv/relative_{}hr_lead_{}hr_obs_data/relative_{}hr_lead_{}hr_obs_temp_feature.csv".format(lead, window, lead, window)):
    df = pd.read_csv("../csv/relative_{}hr_lead_{}hr_obs_data/relative_{}hr_lead_{}hr_obs_temp_feature.csv".format(lead, window, lead, window))
    df = standardize_column_names(df)
    df.to_csv("../csv/relative_{}hr_lead_{}hr_obs_data/relative_{}hr_lead_{}hr_obs_temperature.csv".format(lead, window, lead, window),index=False)
    os.remove("../csv/relative_{}hr_lead_{}hr_obs_data/relative_{}hr_lead_{}hr_obs_temp_feature.csv".format(lead, window, lead, window))
else:
    print("temp_feature")

# Vent
if os.path.isfile("../csv/relative_{}hr_lead_{}hr_obs_data/relative_{}hr_lead_{}hr_obs_vent_feature.csv".format(lead, window, lead, window)):
    df = pd.read_csv("../csv/relative_{}hr_lead_{}hr_obs_data/relative_{}hr_lead_{}hr_obs_vent_feature.csv".format(lead, window, lead, window))
    df = standardize_column_names(df)
    df.to_csv("../csv/relative_{}hr_lead_{}hr_obs_data/relative_{}hr_lead_{}hr_obs_ventilator.csv".format(lead, window, lead, window),index=False)
    os.remove("../csv/relative_{}hr_lead_{}hr_obs_data/relative_{}hr_lead_{}hr_obs_vent_feature.csv".format(lead, window, lead, window))
else:
    print("vent_feature")

# Infection/Sepsis
if os.path.isfile("../csv/relative_{}hr_lead_{}hr_obs_data/relative_{}hr_lead_{}hr_obs_inf_sepsis_feature.csv".format(lead, window, lead, window)):
    df = pd.read_csv("../csv/relative_{}hr_lead_{}hr_obs_data/relative_{}hr_lead_{}hr_obs_inf_sepsis_feature.csv".format(lead, window, lead, window))
    df = standardize_column_names(df)
    df.to_csv("../csv/relative_{}hr_lead_{}hr_obs_data/relative_{}hr_lead_{}hr_obs_infection.csv".format(lead, window, lead, window),index=False)
    os.remove("../csv/relative_{}hr_lead_{}hr_obs_data/relative_{}hr_lead_{}hr_obs_inf_sepsis_feature.csv".format(lead, window, lead, window))
else:
    print("inf_sepsis_feature")


# IO
if os.path.isfile("../csv/relative_{}hr_lead_{}hr_obs_data/relative_{}hr_lead_{}hr_obs_intakeoutput.csv".format(lead, window, lead, window)):
    df = pd.read_csv("../csv/relative_{}hr_lead_{}hr_obs_data/relative_{}hr_lead_{}hr_obs_intakeoutput.csv".format(lead, window, lead, window))
    df = standardize_column_names(df)
    df.to_csv("../csv/relative_{}hr_lead_{}hr_obs_data/relative_{}hr_lead_{}hr_obs_io.csv".format(lead, window, lead, window),index=False)
    os.remove("../csv/relative_{}hr_lead_{}hr_obs_data/relative_{}hr_lead_{}hr_obs_intakeoutput.csv".format(lead, window, lead, window))
else:
    print("intakeoutput")

# Dialysis
if os.path.isfile("../csv/relative_{}hr_lead_{}hr_obs_data/relative_{}hr_lead_{}hr_obs_dialysis.csv".format(lead, window, lead, window)):
    df = pd.read_csv("../csv/relative_{}hr_lead_{}hr_obs_data/relative_{}hr_lead_{}hr_obs_dialysis.csv".format(lead, window, lead, window))
    df = standardize_column_names(df)
    df.to_csv("../csv/relative_{}hr_lead_{}hr_obs_data/relative_{}hr_lead_{}hr_obs_dialysis_feature.csv".format(lead, window, lead, window),index=False)
    os.remove("../csv/relative_{}hr_lead_{}hr_obs_data/relative_{}hr_lead_{}hr_obs_dialysis.csv".format(lead, window, lead, window))
else:
    print("dialysis")

# Surgery
if os.path.isfile("../csv/relative_{}hr_lead_{}hr_obs_data/relative_{}hr_lead_{}hr_obs_surgical.csv".format(lead, window, lead, window)):
    df = pd.read_csv("../csv/relative_{}hr_lead_{}hr_obs_data/relative_{}hr_lead_{}hr_obs_surgical.csv".format(lead, window, lead, window))
    df = standardize_column_names(df)
    df.to_csv("../csv/relative_{}hr_lead_{}hr_obs_data/relative_{}hr_lead_{}hr_obs_surgery.csv".format(lead, window, lead, window),index=False)
    os.remove("../csv/relative_{}hr_lead_{}hr_obs_data/relative_{}hr_lead_{}hr_obs_surgical.csv".format(lead, window, lead, window))
else:
    print("surgical")

# MV Duration
if os.path.isfile("../csv/relative_{}hr_lead_{}hr_obs_data/relative_{}hr_lead_{}hr_obs_MV_duration.csv".format(lead, window, lead, window)):
    df = pd.read_csv("../csv/relative_{}hr_lead_{}hr_obs_data/relative_{}hr_lead_{}hr_obs_MV_duration.csv".format(lead, window, lead, window))
    df = standardize_column_names(df)
    df.to_csv("../csv/relative_{}hr_lead_{}hr_obs_data/relative_{}hr_lead_{}hr_obs_mv.csv".format(lead, window, lead, window),index=False)
    os.remove("../csv/relative_{}hr_lead_{}hr_obs_data/relative_{}hr_lead_{}hr_obs_MV_duration.csv".format(lead, window, lead, window))
else:
    print("MV_duration")

Files Unedited
AKI_feature
AllDrugFeatures
GCS_feature
lab_feature_data
rass_feature
SOFA_features
temp_feature
vent_feature
inf_sepsis_feature
intakeoutput
dialysis
surgical
MV_duration

# Generate Data Set

In [11]:
PTS = False

In [13]:
# Read in Static Data
complete_static = pd.read_csv("../csv/relative_risk_static.csv")

# PatientStayIDs
patientids = pd.read_csv("../csv/relative_{}hr_lead_{}hr_obs_data/relative_{}hr_lead_{}hr_obs_patientstayid_list.csv".format(lead, window, lead, window))

# Merge Static Data
full = patientids.merge(complete_static, how="left", left_on="PatientStayID", right_on="PatientStayID")

# Merge Drugs
drugs = pd.read_csv("../csv/relative_{}hr_lead_{}hr_obs_data/relative_{}hr_lead_{}hr_obs_drug.csv".format(lead, window, lead, window))
drugs.replace(to_replace=[True, False], value=[1, 0], inplace=True)
full = full.merge(drugs, how="left", left_on="PatientStayID", right_on="PatientStayID")

# Merge in Labs
labs = pd.read_csv("../csv/relative_{}hr_lead_{}hr_obs_data/relative_{}hr_lead_{}hr_obs_labs.csv".format(lead, window, lead, window))
full = full.merge(labs, how="left", left_on="PatientStayID", right_on="PatientStayID")

# Merge PTS of applicable
if PTS is True:
    hr = pd.read_csv("../csv/relative_{}hr_lead_{}hr_obs_data/relative_{}hr_lead_{}hr_obs_pts_features_hr.csv".format(lead, window, lead, window))
    if "Unnamed: 0" in hr.columns:
        hr.rename(columns = {"Unnamed: 0" : "PatientStayID"}, inplace=True)
        hr = hr.add_prefix("hr_")
        hr.rename(columns= {"hr_PatientStayID" : "PatientStayID"}, inplace=True)
    full = full.merge(hr, how="inner", left_on="PatientStayID", right_on="PatientStayID")

    resp = pd.read_csv("../csv/relative_{}hr_lead_{}hr_obs_data/relative_{}hr_lead_{}hr_obs_pts_features_resp.csv".format(lead, window, lead, window))
    if "Unnamed: 0" in resp.columns:
        resp.rename(columns = {"Unnamed: 0" : "PatientStayID"}, inplace=True)
        resp = resp.add_prefix("resp_")
        resp.rename(columns= {"resp_PatientStayID" : "PatientStayID"}, inplace=True)
    full = full.merge(resp, how="inner", left_on="PatientStayID", right_on="PatientStayID")

    sao2 = pd.read_csv("../csv/relative_{}hr_lead_{}hr_obs_data/relative_{}hr_lead_{}hr_obs_pts_features_sao2.csv".format(lead, window, lead, window))
    if "Unnamed: 0" in sao2.columns:
        sao2.rename(columns = {"Unnamed: 0" : "PatientStayID"}, inplace=True)
        sao2 = sao2.add_prefix("sao2_")
        sao2.rename(columns= {"sao2_PatientStayID" : "PatientStayID"}, inplace=True)
    full = full.merge(sao2, how="inner", left_on="PatientStayID", right_on="PatientStayID")

# GCS
gcs = pd.read_csv("../csv/relative_{}hr_lead_{}hr_obs_data/relative_{}hr_lead_{}hr_obs_gcs.csv".format(lead, window, lead, window))
full = full.merge(gcs, how="left", left_on="PatientStayID", right_on="PatientStayID")

# Temp
temperature = pd.read_csv("../csv/relative_{}hr_lead_{}hr_obs_data/relative_{}hr_lead_{}hr_obs_temperature.csv".format(lead, window, lead, window))
full = full.merge(temperature, how="left", left_on="PatientStayID", right_on="PatientStayID")

# Ventilator
# ventilator = pd.read_csv("../csv/relative_{}hr_lead_{}hr_obs_data/relative_{}hr_lead_{}hr_obs_ventilator.csv".format(lead, window, lead, window))
# full = full.merge(ventilator, how="left", left_on="PatientStayID", right_on="PatientStayID")


# Rass
rass = pd.read_csv("../csv/relative_{}hr_lead_{}hr_obs_data/relative_{}hr_lead_{}hr_obs_rass.csv".format(lead, window, lead, window))
full = full.merge(rass, how="left", left_on="PatientStayID", right_on="PatientStayID")

# SOFA
sofa = pd.read_csv("../csv/relative_{}hr_lead_{}hr_obs_data/relative_{}hr_lead_{}hr_obs_sofa.csv".format(lead, window, lead, window))
sofa.replace(to_replace=[True, False], value=[1, 0], inplace=True)
full = full.merge(sofa, how="left", left_on="PatientStayID", right_on="PatientStayID")

# Sepsis
infection = pd.read_csv("../csv/relative_{}hr_lead_{}hr_obs_data/relative_{}hr_lead_{}hr_obs_infection.csv".format(lead, window, lead, window))
full = full.merge(infection, how="left", left_on="PatientStayID", right_on="PatientStayID")

#full["sepsis"] = full["infection"] & full["suspected_sepsis"]
#full["septic_shock"] = full["infection"] & full["suspected_septic_shock"]

# AKI
aki = pd.read_csv("../csv/relative_{}hr_lead_{}hr_obs_data/relative_{}hr_lead_{}hr_obs_aki.csv".format(lead, window, lead, window))
full = full.merge(aki, how="left", left_on="PatientStayID", right_on="PatientStayID")


# Comorbidity
comorbidity = pd.read_csv("../csv/relative_{}hr_lead_{}hr_obs_data/relative_{}hr_lead_{}hr_obs_comorbidity.csv".format(lead, window, lead, window))
full = full.merge(comorbidity, how="left", on="PatientStayID")


# io
io = pd.read_csv("../csv/relative_{}hr_lead_{}hr_obs_data/relative_{}hr_lead_{}hr_obs_io.csv".format(lead, window, lead, window))
full = full.merge(io, how="left", on="PatientStayID")


# dialysis
dialysis = pd.read_csv("../csv/relative_{}hr_lead_{}hr_obs_data/relative_{}hr_lead_{}hr_obs_dialysis_feature.csv".format(lead, window, lead, window))
full = full.merge(dialysis, how="left", on="PatientStayID")


# surgery
surgery = pd.read_csv("../csv/relative_{}hr_lead_{}hr_obs_data/relative_{}hr_lead_{}hr_obs_surgery.csv".format(lead, window, lead, window))
full = full.merge(surgery, how="left", on="PatientStayID")

# mv
mv  = pd.read_csv("../csv/relative_{}hr_lead_{}hr_obs_data/relative_{}hr_lead_{}hr_obs_mv.csv".format(lead, window, lead, window))
full = full.merge(mv, how="left", on="PatientStayID")

if PTS is True:
    full.to_csv("../csv/relative_{}hr_lead_{}hr_obs_data/relative_{}hr_lead_{}hr_obs_dataset_with_pts.csv".format(lead, window, lead, window), index = False)
else:
    full.to_csv("../csv/relative_{}hr_lead_{}hr_obs_data/relative_{}hr_lead_{}hr_obs_dataset_no_pts.csv".format(lead, window, lead, window), index = False)

In [14]:
# Create Training/Test Sets
full_dataset = pd.read_csv("../csv/relative_{}hr_lead_{}hr_obs_data/relative_{}hr_lead_{}hr_obs_patientstayid_list.csv".format(lead, window, lead, window))
from sklearn.model_selection import train_test_split, StratifiedKFold
kf = StratifiedKFold(n_splits = 4, shuffle=True, random_state = 150)

count = 1
for train_index, test_index in kf.split(full_dataset, np.zeros(len(full_dataset))):
    if count == 1:
        train_1, test_1 = full_dataset.loc[train_index], full_dataset.loc[test_index]
    elif count == 2:
        train_2, test_2 = full_dataset.loc[train_index], full_dataset.loc[test_index]
    elif count == 3:
        train_3, test_3 = full_dataset.loc[train_index], full_dataset.loc[test_index]
    elif count == 4:
        train_4, test_4 = full_dataset.loc[train_index], full_dataset.loc[test_index]
        
    print(count)
    count+=1

train_1.to_csv("../csv/relative_{}hr_lead_{}hr_obs_data/relative_{}hr_lead_{}hr_obs_training_set_1.csv".format(lead, window, lead, window), index=False)
test_1.to_csv("../csv/relative_{}hr_lead_{}hr_obs_data/relative_{}hr_lead_{}hr_obs_testing_set_1.csv".format(lead, window, lead, window), index=False)

train_2.to_csv("../csv/relative_{}hr_lead_{}hr_obs_data/relative_{}hr_lead_{}hr_obs_training_set_2.csv".format(lead, window, lead, window), index=False)
test_2.to_csv("../csv/relative_{}hr_lead_{}hr_obs_data/relative_{}hr_lead_{}hr_obs_testing_set_2.csv".format(lead, window, lead, window), index=False)

train_3.to_csv("../csv/relative_{}hr_lead_{}hr_obs_data/relative_{}hr_lead_{}hr_obs_training_set_3.csv".format(lead, window, lead, window), index=False)
test_3.to_csv("../csv/relative_{}hr_lead_{}hr_obs_data/relative_{}hr_lead_{}hr_obs_testing_set_3.csv".format(lead, window, lead, window), index=False)

train_4.to_csv("../csv/relative_{}hr_lead_{}hr_obs_data/relative_{}hr_lead_{}hr_obs_training_set_4.csv".format(lead, window, lead, window), index=False)
test_4.to_csv("../csv/relative_{}hr_lead_{}hr_obs_data/relative_{}hr_lead_{}hr_obs_testing_set_4.csv".format(lead, window, lead, window), index=False)


#full_dataset.to_csv("../csv/relative_{}hr_lead_{}hr_obs_data/relative_{}hr_lead_{}hr_obs_{}.csv".format(lead, window, lead, window,data), index=False)

1
2
3
4

In [107]:
## PTS ONLY
patientids = pd.read_csv("../csv/relative_{}hr_lead_{}hr_obs_data/relative_{}hr_lead_{}hr_obs_patientstayid_list.csv".format(lead, window, lead, window))

full = patientids

hr = pd.read_csv("../csv/relative_{}hr_lead_{}hr_obs_data/relative_{}hr_lead_{}hr_obs_pts_features_hr.csv".format(lead, window, lead, window))
if "Unnamed: 0" in hr.columns:
    hr.rename(columns = {"Unnamed: 0" : "PatientStayID"}, inplace=True)
    hr = hr.add_prefix("hr_")
    hr.rename(columns= {"hr_PatientStayID" : "PatientStayID"}, inplace=True)
full = full.merge(hr, how="inner", left_on="PatientStayID", right_on="PatientStayID")

resp = pd.read_csv("../csv/relative_{}hr_lead_{}hr_obs_data/relative_{}hr_lead_{}hr_obs_pts_features_resp.csv".format(lead, window, lead, window))
if "Unnamed: 0" in resp.columns:
    resp.rename(columns = {"Unnamed: 0" : "PatientStayID"}, inplace=True)
    resp = resp.add_prefix("resp_")
    resp.rename(columns= {"resp_PatientStayID" : "PatientStayID"}, inplace=True)
full = full.merge(resp, how="inner", left_on="PatientStayID", right_on="PatientStayID")

sao2 = pd.read_csv("../csv/relative_{}hr_lead_{}hr_obs_data/relative_{}hr_lead_{}hr_obs_pts_features_sao2.csv".format(lead, window, lead, window))
if "Unnamed: 0" in sao2.columns:
    sao2.rename(columns = {"Unnamed: 0" : "PatientStayID"}, inplace=True)
    sao2 = sao2.add_prefix("sao2_")
    sao2.rename(columns= {"sao2_PatientStayID" : "PatientStayID"}, inplace=True)
full = full.merge(sao2, how="inner", left_on="PatientStayID", right_on="PatientStayID")

full.to_csv("../csv/relative_{}hr_lead_{}hr_obs_data/relative_{}hr_lead_{}hr_obs_dataset_pts_only.csv".format(lead, window, lead, window), index = False)

In [33]:
# Format PatientStayID List
patientids = pd.read_csv("../csv/relative_{}hr_lead_{}hr_obs_data/relative_{}hr_lead_{}hr_obs_data_set.csv".format(lead, window, lead, window))
patientids.drop(["start", "end"], axis=1, inplace=True)
patientids.rename(columns={"patientunitstayid" : "PatientStayID", "delirium?" : "Class"}, inplace=True)
patientids.to_csv("../csv/relative_{}hr_lead_{}hr_obs_data/relative_{}hr_lead_{}hr_obs_patientstayid_list.csv".format(lead, window, lead, window), index=False)
patientids

       PatientStayID  Class
0             150934      1
1             151213      1
2             151708      1
3             152171      1
4             155126      1
...              ...    ...
23477        3352487      0
23478        3352563      0
23479        3352747      0
23480        3353044      0
23481        3353077      0

[23482 rows x 2 columns]

In [35]:
# Format Drugs
drugs = pd.read_csv("../csv/relative_{}hr_lead_{}hr_obs_data/relative_{}hr_lead_{}hr_obs_drug.csv".format(lead, window, lead, window))
drugs.drop(["Unnamed: 0", "delirium?", "start", "end"], axis=1, inplace=True)
drugs.rename(columns={"patientunitstayid" : "PatientStayID"}, inplace=True)
drugs.to_csv("../csv/relative_{}hr_lead_{}hr_obs_data/relative_{}hr_lead_{}hr_obs_drug.csv".format(lead, window, lead, window), index=False)
drugs

,PatientStayID,relative_1hr_lead_1hr_obsAdrenergicBronchodilators,relative_1hr_lead_1hr_obsaminoglycosides,relative_1hr_lead_1hr_obsAnticholinergicBronchodilators,relative_1hr_lead_1hr_obsAnticholinergics,relative_1hr_lead_1hr_obsAnticoagulants,relative_1hr_lead_1hr_obsAntidiarrheals,relative_1hr_lead_1hr_obsAntiemetics,relative_1hr_lead_1hr_obsAntihistamines,relative_1hr_lead_1hr_obsBarbiturates,...,relative_1hr_lead_1hr_obsSodiumChannelBlockers,relative_1hr_lead_1hr_obsSomatostatin,relative_1hr_lead_1hr_obsSSRIAntidepressants,relative_1hr_lead_1hr_obsSulfonamides,relative_1hr_lead_1hr_obsTetracyclicAntidepressants,relative_1hr_lead_1hr_obsTetracyclines,relative_1hr_lead_1hr_obsThrombolytics,relative_1hr_lead_1hr_obsTricyclicAntidepressants,relative_1hr_lead_1hr_obsVasodilators,relative_1hr_lead_1hr_obsVasopressors
0,150934,False,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
1,151213,True,False,True,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,True
2,151708,True,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,True,False,True,False
3,152171,False,False,False,False,True,False,True,True,False,...,False,False,False,False,False,False,False,False,True,False
4,155126,True,False,True,False,False,False,True,False,False,...,False,False,False,False,False,False,True,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23477,3352487,True,False,True,False,True,False,True,True,False,...,False,False,False,False,True,False,False,False,False,False
23478,3352563,False,False,False,False,True,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
23479,3352747,False,False,False,False,False,False,True,False,False,...,False,False,False,False,True,False,False,False,False,False
23480,3353044,False,False,False,False,True,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
23481,3353077,True,False,True,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False

In [38]:
# FOrmat GCS
gcs = pd.read_csv("../csv/relative_{}hr_lead_{}hr_obs_data/relative_{}hr_lead_{}hr_obs_gcs.csv".format(lead, window, lead, window))
gcs.rename(columns={"patientunitstayid" : "PatientStayID"}, inplace=True)
gcs.to_csv("../csv/relative_{}hr_lead_{}hr_obs_data/relative_{}hr_lead_{}hr_obs_gcs.csv".format(lead, window, lead, window), index=False)
gcs

,PatientStayID,last_motor_GCS,last_verbal_GCS,last_eyes_GCS,last_total_GCS
0,150934,NaN,NaN,NaN,10.0
1,151213,5.0,2.0,3.0,10.0
2,151708,NaN,NaN,NaN,14.0
3,152171,NaN,NaN,NaN,14.0
4,155126,NaN,NaN,NaN,9.0
...,...,...,...,...,...
23477,3352487,NaN,NaN,NaN,NaN
23478,3352563,NaN,NaN,NaN,8.0
23479,3352747,NaN,NaN,NaN,NaN
23480,3353044,NaN,NaN,NaN,14.0
23481,3353077,NaN,NaN,NaN,15.0

In [39]:
# FOrmat temperature
temperature = pd.read_csv("../csv/relative_{}hr_lead_{}hr_obs_data/relative_{}hr_lead_{}hr_obs_temp.csv".format(lead, window, lead, window))
temperature.rename(columns={"patientunitstayid" : "PatientStayID"}, inplace=True)
temperature.to_csv("../csv/relative_{}hr_lead_{}hr_obs_data/relative_{}hr_lead_{}hr_obs_temp.csv".format(lead, window, lead, window), index=False)
temperature

       PatientStayID  last_temp
0             150934       37.4
1             151213       36.8
2             151708       36.9
3             152171       37.8
4             155126       37.1
...              ...        ...
23477        3352487       36.9
23478        3352563       36.8
23479        3352747       36.4
23480        3353044       36.9
23481        3353077       36.9

[23482 rows x 2 columns]

In [70]:
# Format SOFA
sofa = pd.read_csv("../csv/relative_{}hr_lead_{}hr_obs_data/relative_{}hr_lead_{}hr_obs_sofa.csv".format(lead, window, lead, window))
sofa.drop(["Unnamed: 0"], axis=1, inplace=True)
sofa.drop(sofa.columns[1:26], axis=1, inplace=True)
sofa.rename(columns={"patientunitstayid" : "PatientStayID"}, inplace=True)
sofa.to_csv("../csv/relative_{}hr_lead_{}hr_obs_data/relative_{}hr_lead_{}hr_obs_sofa.csv".format(lead, window, lead, window), index=False)
sofa

KeyError: "['Unnamed: 0'] not found in axis"

In [71]:
# Format Rass
rass = pd.read_csv("../csv/relative_{}hr_lead_{}hr_obs_data/relative_{}hr_lead_{}hr_obs_rass.csv".format(lead, window, lead, window))
rass.drop(columns=["Unnamed: 0"], inplace=True)
rass.rename(columns={"patientunitstayid" : "PatientStayID"}, inplace=True)
rass.to_csv("../csv/relative_{}hr_lead_{}hr_obs_data/relative_{}hr_lead_{}hr_obs_rass.csv".format(lead, window, lead, window), index=False)
rass

       PatientStayID  last_rass
0             150934        NaN
1             151213        NaN
2             151708        NaN
3             152171        NaN
4             155126        NaN
...              ...        ...
21880        3352487        NaN
21881        3352563        NaN
21882        3352747        NaN
21883        3353044        NaN
21884        3353077        NaN

[21885 rows x 2 columns]

In [72]:
# Format Sepsis
sepsis = pd.read_csv("../csv/relative_{}hr_lead_{}hr_obs_data/relative_{}hr_lead_{}hr_obs_sepsis.csv".format(lead, window, lead, window))
sepsis.drop(columns=["Unnamed: 0"], inplace=True)
sepsis.rename(columns={"patientunitstayid": "PatientStayID"}, inplace=True)
sepsis.replace(to_replace=[True, False], value=[1, 0], inplace=True)
sepsis.to_csv("../csv/relative_{}hr_lead_{}hr_obs_data/relative_{}hr_lead_{}hr_obs_sepsis.csv".format(lead, window, lead, window), index=False)
sepsis

,PatientStayID,infection,suspected_sepsis,sepsis,suspected_septic_shock,septic_shock
0,150934,0,1,0,0,0
1,151213,0,1,0,0,0
2,151708,0,0,0,0,0
3,152171,0,0,0,0,0
4,155126,0,0,0,0,0
...,...,...,...,...,...,...
21880,3352487,0,0,0,0,0
21881,3352563,0,0,0,0,0
21882,3352747,0,0,0,0,0
21883,3353044,0,1,0,0,0
21884,3353077,0,0,0,0,0

In [43]:
# Format Comorbidity
comorbidity = pd.read_csv("../csv/relative_{}hr_lead_{}hr_obs_data/relative_{}hr_lead_{}hr_obs_comorbidity.csv".format(lead, window, lead, window))
comorbidity.drop(["Unnamed: 0"], axis=1, inplace=True)
comorbidity = comorbidity.iloc[:, :32]
comorbidity.drop(["psycho"], axis=1, inplace=True)
comorbidity = comorbidity.add_prefix("comorbidity_")
comorbidity.rename(columns={"comorbidity_patientunitstayid" : "PatientStayID"}, inplace=True)
comorbidity.to_csv("../csv/relative_{}hr_lead_{}hr_obs_data/relative_{}hr_lead_{}hr_obs_comorbidity.csv".format(lead, window, lead, window), index=False)
comorbidity

,PatientStayID,comorbidity_chf,comorbidity_carit,comorbidity_valv,comorbidity_pcd,comorbidity_pvd,comorbidity_hypunc,comorbidity_hypc,comorbidity_para,comorbidity_ond,...,comorbidity_rheumd,comorbidity_coag,comorbidity_obes,comorbidity_wloss,comorbidity_fed,comorbidity_blane,comorbidity_dane,comorbidity_alcohol,comorbidity_drug,comorbidity_depre
0,150934,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,151213,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,151708,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
3,152171,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,155126,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18705,3352747,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18706,3352819,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18707,3353044,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
18708,3353077,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18709,3353097,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [73]:
# Format AKI
aki = pd.read_csv("../csv/relative_{}hr_lead_{}hr_obs_data/relative_{}hr_lead_{}hr_obs_aki.csv".format(lead, window, lead, window))
aki.drop(columns=["Unnamed: 0"], inplace=True)
aki.rename(columns={"patientunitstayid": "PatientStayID"}, inplace=True)
aki.replace(to_replace=[True, False], value=[1, 0], inplace=True)
aki.to_csv("../csv/relative_{}hr_lead_{}hr_obs_data/relative_{}hr_lead_{}hr_obs_aki.csv".format(lead, window, lead, window),index=False)
aki

       PatientStayID  AKI
0             150934    0
1             151213    0
2             151708    0
3             152171    0
4             155126    0
...              ...  ...
21880        3352487    0
21881        3352563    0
21882        3352747    0
21883        3353044    0
21884        3353077    0

[21885 rows x 2 columns]

In [12]:
import glob
labs = glob.glob("../csv/relative_{}hr_labs/*".format(window))

for lab in labs:
    lab_df = pd.read_csv(lab)
    lab_df.rename(columns={'patientunitstayid' : "PatientStayID"}, inplace=True)
    full = full.merge(lab_df, how="inner", left_on="PatientStayID", right_on="PatientStayID")
full

,PatientStayID,Class,Age,APACHEIVscore,APACHEIVaScore,UrgentAdmission,AdmissionCategory,NumBeds,TeachingStatus,Gender,...,max_sodium,mean_total bilirubin,min_total bilirubin,max_total bilirubin,mean_total protein,min_total protein,max_total protein,mean_WBC x 1000,min_WBC x 1000,max_WBC x 1000
0,151708,1,79.0,38.0,38.0,0.0,4.0,4.0,1,Male,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,152171,1,84.0,38.0,38.0,1.0,4.0,2.0,0,Female,...,138.0,NaN,NaN,NaN,NaN,NaN,NaN,7.10,7.1,7.1
2,155126,1,71.0,65.0,65.0,1.0,4.0,4.0,1,Male,...,147.0,NaN,NaN,NaN,NaN,NaN,NaN,13.10,13.1,13.1
3,156970,1,56.0,32.0,32.0,0.0,4.0,4.0,1,Male,...,139.0,NaN,NaN,NaN,NaN,NaN,NaN,10.30,10.3,10.3
4,165069,1,84.0,46.0,46.0,0.0,2.0,2.0,0,Male,...,142.0,NaN,NaN,NaN,NaN,NaN,NaN,7.80,7.8,7.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13981,3350678,0,60.0,52.0,52.0,0.0,4.0,4.0,0,Male,...,137.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13982,3351363,0,90.0,NaN,NaN,0.0,4.0,4.0,0,Female,...,138.0,NaN,NaN,NaN,NaN,NaN,NaN,3.80,3.8,3.8
13983,3352331,0,75.0,48.0,48.0,0.0,4.0,2.0,0,Female,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.15,8.4,9.9
13984,3353044,0,52.0,41.0,41.0,0.0,4.0,2.0,0,Male,...,128.0,NaN,NaN,NaN,NaN,NaN,NaN,10.20,10.2,10.2
13985,3353077,0,60.0,36.0,36.0,0.0,4.0,4.0,0,Female,...,143.0,NaN,NaN,NaN,NaN,NaN,NaN,15.45,14.5,16.4

In [55]:
hr = pd.read_csv("../csv/relative_{}hr_pts_hr.csv".format(window))
hr

,PatientStayID,hr_value__abs_energy,hr_value__absolute_sum_of_changes,"hr_value__agg_autocorrelation__f_agg_""mean""__maxlag_40","hr_value__agg_autocorrelation__f_agg_""median""__maxlag_40","hr_value__agg_autocorrelation__f_agg_""var""__maxlag_40","hr_value__agg_linear_trend__attr_""intercept""__chunk_len_10__f_agg_""max""","hr_value__agg_linear_trend__attr_""intercept""__chunk_len_10__f_agg_""mean""","hr_value__agg_linear_trend__attr_""intercept""__chunk_len_10__f_agg_""min""","hr_value__agg_linear_trend__attr_""intercept""__chunk_len_10__f_agg_""var""",...,hr_value__symmetry_looking__r_0.9500000000000001,hr_value__time_reversal_asymmetry_statistic__lag_1,hr_value__time_reversal_asymmetry_statistic__lag_2,hr_value__time_reversal_asymmetry_statistic__lag_3,hr_value__value_count__value_-1,hr_value__value_count__value_0,hr_value__value_count__value_1,hr_value__variance,hr_value__variance_larger_than_standard_deviation,hr_value__variation_coefficient
0,151708,1.432944e+06,566.000000,0.380182,0.389317,0.016731,66.386207,65.289310,63.351724,-1.195592,...,1,540.467237,1013.557903,1478.118203,0,0,0,21.882668,1,0.066464
1,152171,1.298502e+06,365.000000,0.179560,0.125335,0.032699,67.868966,65.712414,62.048276,8.283793,...,1,651.069686,1176.333333,1555.254417,0,0,0,16.596808,1,0.060890
2,155126,2.139491e+06,888.000000,0.202346,0.017950,0.115421,84.482759,81.246552,77.600000,-17.466879,...,1,-1656.468531,-3562.098592,-5165.627660,0,0,0,270.335636,1,0.194331
3,156970,1.895176e+06,438.000000,0.732306,0.748930,0.013670,99.517241,93.069310,88.827586,12.488155,...,1,-620.223776,-1430.140845,-2451.432624,0,0,0,86.798611,1,0.115614
4,165069,7.969934e+05,463.000000,0.659233,0.622461,0.013340,46.834483,44.987069,43.486207,1.381728,...,1,45.634834,263.832196,761.783910,0,0,0,40.358938,1,0.121655
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13612,3351580,8.894701e+05,578.917808,0.572357,0.595540,0.018776,58.243944,52.012538,48.079999,11.279466,...,1,-5.412550,146.730154,183.364112,0,0,0,50.142430,1,0.125022
13613,3352331,1.360252e+06,462.000000,0.079655,0.008651,0.060335,74.800000,70.275361,66.904075,6.976473,...,1,-534.459169,-1017.521293,-1603.283376,0,0,0,13.228444,1,0.052997
13614,3353044,1.024471e+06,832.000000,0.471310,0.423679,0.020402,56.078261,48.112631,42.632084,26.106365,...,1,2946.256428,5388.771169,7697.985151,0,0,0,105.627415,1,0.174937
13615,3353077,1.577917e+06,295.000000,0.497388,0.521502,0.072355,73.688756,73.899768,73.424888,-1.998932,...,1,-138.134034,-173.091156,-113.985803,0,0,0,51.587976,1,0.097495
13616,3353197,2.670033e+06,410.000000,0.596493,0.579754,0.013214,92.841379,90.600690,89.751724,-1.758245,...,1,829.839721,1399.585965,2171.621908,0,0,0,30.175022,1,0.057243

In [24]:
temp = pd.read_csv("../csv/relative_{}hr_pts_sao2.csv".format(3))
temp = temp.add_prefix("sao2_")
temp

,sao2_id,sao2_value__abs_energy,sao2_value__absolute_sum_of_changes,"sao2_value__agg_autocorrelation__f_agg_""mean""__maxlag_40","sao2_value__agg_autocorrelation__f_agg_""median""__maxlag_40","sao2_value__agg_autocorrelation__f_agg_""var""__maxlag_40","sao2_value__agg_linear_trend__attr_""intercept""__chunk_len_10__f_agg_""max""","sao2_value__agg_linear_trend__attr_""intercept""__chunk_len_10__f_agg_""mean""","sao2_value__agg_linear_trend__attr_""intercept""__chunk_len_10__f_agg_""min""","sao2_value__agg_linear_trend__attr_""intercept""__chunk_len_10__f_agg_""var""",...,sao2_value__symmetry_looking__r_0.9500000000000001,sao2_value__time_reversal_asymmetry_statistic__lag_1,sao2_value__time_reversal_asymmetry_statistic__lag_2,sao2_value__time_reversal_asymmetry_statistic__lag_3,sao2_value__value_count__value_-1,sao2_value__value_count__value_0,sao2_value__value_count__value_1,sao2_value__variance,sao2_value__variance_larger_than_standard_deviation,sao2_value__variation_coefficient
0,151708,2.784331e+06,224.000000,0.028050,0.000902,0.009378,99.000000,98.615092,96.951724,0.586686,...,1.0,-4.403702,-2.550921,-70.570868,0.0,0.0,0.0,3.492975,1.0,0.019011
1,152171,2.670068e+06,203.000000,0.099426,0.058422,0.023783,96.950575,95.643247,94.329885,0.275977,...,1.0,-921.764016,-1316.192121,-1102.734605,0.0,0.0,0.0,5.042670,1.0,0.023369
2,155126,2.669206e+06,180.666667,0.293979,0.244479,0.033382,97.967816,97.301172,95.567816,0.001789,...,1.0,589.591954,1100.801819,1532.587099,0.0,0.0,0.0,13.034184,1.0,0.037528
3,156970,2.633670e+06,153.000000,0.206089,0.065404,0.074768,95.544828,94.455172,93.082759,1.053517,...,1.0,564.931163,1077.392716,1537.210771,0.0,0.0,0.0,4.198420,1.0,0.021432
4,165069,2.553515e+06,295.000000,0.111553,0.054081,0.024960,96.546552,96.053621,94.875862,-2.640030,...,1.0,-232.104078,-1830.392373,-3981.735077,0.0,0.0,0.0,10.452085,1.0,0.034355
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13374,3351580,2.609687e+06,59.418919,0.608164,0.552793,0.014559,97.376448,96.734010,96.088603,0.208346,...,1.0,84.030972,180.810100,290.617030,0.0,0.0,0.0,0.859469,0.0,0.009482
13375,3352331,2.577869e+06,206.000000,0.078031,0.061138,0.016048,96.862069,95.065862,92.896552,1.647534,...,1.0,246.916084,427.771127,557.436170,0.0,0.0,0.0,1.642638,1.0,0.013548
13376,3353044,2.645771e+06,105.537100,0.337296,0.175253,0.082770,102.283054,103.620079,105.260690,-12.574129,...,1.0,-2751.854379,-5621.590163,-8602.665664,0.0,0.0,0.0,74.981720,1.0,0.090715
13377,3353077,2.723053e+06,91.000000,0.337522,0.297471,0.035613,97.087631,96.757735,96.396402,0.157896,...,1.0,134.759064,273.030623,481.106719,0.0,0.0,0.0,1.433757,1.0,0.012294
13378,3353197,2.708031e+06,145.257143,0.479481,0.514102,0.029637,98.962562,99.053399,98.750739,-0.796649,...,1.0,166.374850,328.098353,483.950595,0.0,0.0,0.0,7.466127,1.0,0.028239

In [25]:
temp.to_csv("../csv/relative_{}hr_pts_sao2.csv".format(3))

In [56]:
full = full.merge(hr, how="inner", left_on="PatientStayID", right_on="PatientStayID")
full

,PatientStayID,Class,Age,APACHEIVscore,APACHEIVaScore,UrgentAdmission,AdmissionCategory,NumBeds,TeachingStatus,Gender,...,hr_value__symmetry_looking__r_0.9500000000000001,hr_value__time_reversal_asymmetry_statistic__lag_1,hr_value__time_reversal_asymmetry_statistic__lag_2,hr_value__time_reversal_asymmetry_statistic__lag_3,hr_value__value_count__value_-1,hr_value__value_count__value_0,hr_value__value_count__value_1,hr_value__variance,hr_value__variance_larger_than_standard_deviation,hr_value__variation_coefficient
0,151708,1,79.0,38.0,38.0,0.0,4.0,4.0,1,Male,...,1,540.467237,1013.557903,1478.118203,0,0,0,21.882668,1,0.066464
1,152171,1,84.0,38.0,38.0,1.0,4.0,2.0,0,Female,...,1,651.069686,1176.333333,1555.254417,0,0,0,16.596808,1,0.060890
2,155126,1,71.0,65.0,65.0,1.0,4.0,4.0,1,Male,...,1,-1656.468531,-3562.098592,-5165.627660,0,0,0,270.335636,1,0.194331
3,156970,1,56.0,32.0,32.0,0.0,4.0,4.0,1,Male,...,1,-620.223776,-1430.140845,-2451.432624,0,0,0,86.798611,1,0.115614
4,165069,1,84.0,46.0,46.0,0.0,2.0,2.0,0,Male,...,1,45.634834,263.832196,761.783910,0,0,0,40.358938,1,0.121655
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13612,3350678,0,60.0,52.0,52.0,0.0,4.0,4.0,0,Male,...,1,422.370500,718.937793,948.920804,0,0,0,50.756450,1,0.088696
13613,3351363,0,90.0,NaN,NaN,0.0,4.0,4.0,0,Female,...,1,1075.470595,4452.601755,6016.377431,0,0,0,510.575227,1,0.294863
13614,3352331,0,75.0,48.0,48.0,0.0,4.0,2.0,0,Female,...,1,-534.459169,-1017.521293,-1603.283376,0,0,0,13.228444,1,0.052997
13615,3353044,0,52.0,41.0,41.0,0.0,4.0,2.0,0,Male,...,1,2946.256428,5388.771169,7697.985151,0,0,0,105.627415,1,0.174937
13616,3353077,0,60.0,36.0,36.0,0.0,4.0,4.0,0,Female,...,1,-138.134034,-173.091156,-113.985803,0,0,0,51.587976,1,0.097495

In [57]:
resp = pd.read_csv("../csv/relative_{}hr_pts_resp.csv".format(window))
resp

,PatientStayID,resp_value__abs_energy,resp_value__absolute_sum_of_changes,"resp_value__agg_autocorrelation__f_agg_""mean""__maxlag_40","resp_value__agg_autocorrelation__f_agg_""median""__maxlag_40","resp_value__agg_autocorrelation__f_agg_""var""__maxlag_40","resp_value__agg_linear_trend__attr_""intercept""__chunk_len_10__f_agg_""max""","resp_value__agg_linear_trend__attr_""intercept""__chunk_len_10__f_agg_""mean""","resp_value__agg_linear_trend__attr_""intercept""__chunk_len_10__f_agg_""min""","resp_value__agg_linear_trend__attr_""intercept""__chunk_len_10__f_agg_""var""",...,resp_value__symmetry_looking__r_0.9500000000000001,resp_value__time_reversal_asymmetry_statistic__lag_1,resp_value__time_reversal_asymmetry_statistic__lag_2,resp_value__time_reversal_asymmetry_statistic__lag_3,resp_value__value_count__value_-1,resp_value__value_count__value_0,resp_value__value_count__value_1,resp_value__variance,resp_value__variance_larger_than_standard_deviation,resp_value__variation_coefficient
0,151708,57983.55556,556.000000,0.134084,0.118639,0.012763,16.903333,14.288667,11.016667,3.485126,...,1,12.818680,17.322612,35.071780,0,0,0,12.609782,1,0.230509
1,152171,121666.57780,661.000000,0.482076,0.487694,0.019530,28.351724,21.205517,15.227586,17.495418,...,1,21.766948,52.877277,90.773191,0,0,0,36.614564,1,0.308637
2,155126,157730.84360,967.640000,0.145885,0.166985,0.039198,36.470621,26.790359,19.188414,32.553348,...,1,-176.519900,-522.956729,-674.028425,0,0,0,58.151696,1,0.344662
3,156970,110256.00000,432.000000,0.624888,0.610407,0.005651,30.324138,25.212241,22.193103,7.563004,...,1,-32.951049,-68.161972,-122.882979,0,0,0,24.730276,1,0.262791
4,165069,149154.11550,317.710280,0.219069,0.140993,0.025964,26.557312,23.243933,20.051550,3.954556,...,1,-2.594383,-35.319382,-45.475100,0,0,0,5.715561,1,0.105637
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10786,3351580,137381.79910,858.356164,0.269064,0.250649,0.011744,27.110399,18.282163,13.799480,20.020287,...,1,-32.192366,-29.336930,-4.263125,0,0,0,33.295137,1,0.266178
10787,3352331,148971.97730,1161.000000,0.103540,0.084603,0.012692,35.724138,24.743386,13.144828,51.277205,...,1,-57.030305,-107.042332,-147.782369,0,0,0,48.496205,1,0.321644
10788,3353044,174578.78260,1101.000000,0.082250,0.067387,0.008150,35.591304,24.784918,19.057271,35.585509,...,1,57.796178,83.900140,162.988105,0,0,0,34.833543,1,0.246917
10789,3353077,207799.25000,551.000000,0.210403,0.184241,0.037091,29.586207,26.324828,24.675862,14.941517,...,1,-396.327797,-503.818662,-414.274823,0,0,0,24.876805,1,0.188969
10790,3353197,147607.25000,890.000000,0.033920,-0.018046,0.016264,29.758621,23.682414,18.358621,13.246190,...,1,-27.941638,-32.874561,-43.706714,0,0,0,18.572132,1,0.194254

In [58]:
full = full.merge(resp, how="inner", left_on="PatientStayID", right_on="PatientStayID")
full

,PatientStayID,Class,Age,APACHEIVscore,APACHEIVaScore,UrgentAdmission,AdmissionCategory,NumBeds,TeachingStatus,Gender,...,resp_value__symmetry_looking__r_0.9500000000000001,resp_value__time_reversal_asymmetry_statistic__lag_1,resp_value__time_reversal_asymmetry_statistic__lag_2,resp_value__time_reversal_asymmetry_statistic__lag_3,resp_value__value_count__value_-1,resp_value__value_count__value_0,resp_value__value_count__value_1,resp_value__variance,resp_value__variance_larger_than_standard_deviation,resp_value__variation_coefficient
0,151708,1,79.0,38.0,38.0,0.0,4.0,4.0,1,Male,...,1,12.818680,17.322612,35.071780,0,0,0,12.609782,1,0.230509
1,152171,1,84.0,38.0,38.0,1.0,4.0,2.0,0,Female,...,1,21.766948,52.877277,90.773191,0,0,0,36.614564,1,0.308637
2,155126,1,71.0,65.0,65.0,1.0,4.0,4.0,1,Male,...,1,-176.519900,-522.956729,-674.028425,0,0,0,58.151696,1,0.344662
3,156970,1,56.0,32.0,32.0,0.0,4.0,4.0,1,Male,...,1,-32.951049,-68.161972,-122.882979,0,0,0,24.730276,1,0.262791
4,165069,1,84.0,46.0,46.0,0.0,2.0,2.0,0,Male,...,1,-2.594383,-35.319382,-45.475100,0,0,0,5.715561,1,0.105637
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10786,3350678,0,60.0,52.0,52.0,0.0,4.0,4.0,0,Male,...,1,-8.358585,-41.016371,-41.222240,0,0,0,78.853146,1,0.424151
10787,3351363,0,90.0,NaN,NaN,0.0,4.0,4.0,0,Female,...,1,-15.905583,-14.103517,15.423987,0,0,0,29.786557,1,0.307476
10788,3352331,0,75.0,48.0,48.0,0.0,4.0,2.0,0,Female,...,1,-57.030305,-107.042332,-147.782369,0,0,0,48.496205,1,0.321644
10789,3353044,0,52.0,41.0,41.0,0.0,4.0,2.0,0,Male,...,1,57.796178,83.900140,162.988105,0,0,0,34.833543,1,0.246917
10790,3353077,0,60.0,36.0,36.0,0.0,4.0,4.0,0,Female,...,1,-396.327797,-503.818662,-414.274823,0,0,0,24.876805,1,0.188969

In [59]:
sao2 = pd.read_csv("../csv/relative_{}hr_pts_sao2.csv".format(window))
sao2

,PatientStayID,sao2_value__abs_energy,sao2_value__absolute_sum_of_changes,"sao2_value__agg_autocorrelation__f_agg_""mean""__maxlag_40","sao2_value__agg_autocorrelation__f_agg_""median""__maxlag_40","sao2_value__agg_autocorrelation__f_agg_""var""__maxlag_40","sao2_value__agg_linear_trend__attr_""intercept""__chunk_len_10__f_agg_""max""","sao2_value__agg_linear_trend__attr_""intercept""__chunk_len_10__f_agg_""mean""","sao2_value__agg_linear_trend__attr_""intercept""__chunk_len_10__f_agg_""min""","sao2_value__agg_linear_trend__attr_""intercept""__chunk_len_10__f_agg_""var""",...,sao2_value__symmetry_looking__r_0.9500000000000001,sao2_value__time_reversal_asymmetry_statistic__lag_1,sao2_value__time_reversal_asymmetry_statistic__lag_2,sao2_value__time_reversal_asymmetry_statistic__lag_3,sao2_value__value_count__value_-1,sao2_value__value_count__value_0,sao2_value__value_count__value_1,sao2_value__variance,sao2_value__variance_larger_than_standard_deviation,sao2_value__variation_coefficient
0,151708,2784331.172,224.000000,0.028050,0.000902,0.009378,99.000000,98.615092,96.951724,0.586686,...,1,-4.403702,-2.550921,-70.570868,0,0,0,3.492975,1,0.019011
1,152171,2670067.854,203.000000,0.099426,0.058422,0.023783,96.950575,95.643247,94.329885,0.275977,...,1,-921.764016,-1316.192121,-1102.734605,0,0,0,5.042670,1,0.023369
2,155126,2669205.728,180.666667,0.293979,0.244479,0.033382,97.967816,97.301172,95.567816,0.001789,...,1,589.591954,1100.801819,1532.587099,0,0,0,13.034184,1,0.037528
3,156970,2633669.875,153.000000,0.206089,0.065404,0.074768,95.544828,94.455172,93.082759,1.053517,...,1,564.931163,1077.392716,1537.210771,0,0,0,4.198420,1,0.021432
4,165069,2553515.431,295.000000,0.111553,0.054081,0.024960,96.546552,96.053621,94.875862,-2.640030,...,1,-232.104078,-1830.392373,-3981.735077,0,0,0,10.452085,1,0.034355
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13374,3351580,2609687.478,59.418919,0.608164,0.552793,0.014559,97.376448,96.734010,96.088603,0.208346,...,1,84.030972,180.810100,290.617030,0,0,0,0.859469,0,0.009482
13375,3352331,2577869.000,206.000000,0.078031,0.061138,0.016048,96.862069,95.065862,92.896552,1.647534,...,1,246.916084,427.771127,557.436170,0,0,0,1.642638,1,0.013548
13376,3353044,2645770.604,105.537100,0.337296,0.175253,0.082770,102.283054,103.620079,105.260690,-12.574129,...,1,-2751.854379,-5621.590163,-8602.665664,0,0,0,74.981720,1,0.090715
13377,3353077,2723053.168,91.000000,0.337522,0.297471,0.035613,97.087631,96.757735,96.396402,0.157896,...,1,134.759064,273.030623,481.106719,0,0,0,1.433757,1,0.012294
13378,3353197,2708030.654,145.257143,0.479481,0.514102,0.029637,98.962562,99.053399,98.750739,-0.796649,...,1,166.374850,328.098353,483.950595,0,0,0,7.466127,1,0.028239

In [60]:
full = full.merge(sao2, how="inner", left_on="PatientStayID", right_on="PatientStayID")
full

,PatientStayID,Class,Age,APACHEIVscore,APACHEIVaScore,UrgentAdmission,AdmissionCategory,NumBeds,TeachingStatus,Gender,...,sao2_value__symmetry_looking__r_0.9500000000000001,sao2_value__time_reversal_asymmetry_statistic__lag_1,sao2_value__time_reversal_asymmetry_statistic__lag_2,sao2_value__time_reversal_asymmetry_statistic__lag_3,sao2_value__value_count__value_-1,sao2_value__value_count__value_0,sao2_value__value_count__value_1,sao2_value__variance,sao2_value__variance_larger_than_standard_deviation,sao2_value__variation_coefficient
0,151708,1,79.0,38.0,38.0,0.0,4.0,4.0,1,Male,...,1,-4.403702,-2.550921,-70.570868,0,0,0,3.492975,1,0.019011
1,152171,1,84.0,38.0,38.0,1.0,4.0,2.0,0,Female,...,1,-921.764016,-1316.192121,-1102.734605,0,0,0,5.042670,1,0.023369
2,155126,1,71.0,65.0,65.0,1.0,4.0,4.0,1,Male,...,1,589.591954,1100.801819,1532.587099,0,0,0,13.034184,1,0.037528
3,156970,1,56.0,32.0,32.0,0.0,4.0,4.0,1,Male,...,1,564.931163,1077.392716,1537.210771,0,0,0,4.198420,1,0.021432
4,165069,1,84.0,46.0,46.0,0.0,2.0,2.0,0,Male,...,1,-232.104078,-1830.392373,-3981.735077,0,0,0,10.452085,1,0.034355
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10674,3350678,0,60.0,52.0,52.0,0.0,4.0,4.0,0,Male,...,1,0.000688,0.022716,126.051876,0,0,0,0.948470,0,0.010290
10675,3351363,0,90.0,NaN,NaN,0.0,4.0,4.0,0,Female,...,1,-2.011448,-4.725388,124.558975,0,0,0,17.126652,1,0.043339
10676,3352331,0,75.0,48.0,48.0,0.0,4.0,2.0,0,Female,...,1,246.916084,427.771127,557.436170,0,0,0,1.642638,1,0.013548
10677,3353044,0,52.0,41.0,41.0,0.0,4.0,2.0,0,Male,...,1,-2751.854379,-5621.590163,-8602.665664,0,0,0,74.981720,1,0.090715
10678,3353077,0,60.0,36.0,36.0,0.0,4.0,4.0,0,Female,...,1,134.759064,273.030623,481.106719,0,0,0,1.433757,1,0.012294

In [13]:
gcs = pd.read_csv("../csv/relative_{}hr_GCS_feature.csv".format(window))
gcs

,PatientStayID,mean_motor_GCS,mean_verbal_GCS,mean_eyes_GCS,mean_total_GCS
0,151708,NaN,NaN,NaN,13.933333
1,152171,NaN,NaN,NaN,14.000000
2,155126,NaN,NaN,NaN,11.333333
3,156970,NaN,NaN,NaN,14.000000
4,165069,NaN,NaN,NaN,15.000000
...,...,...,...,...,...
13981,3350678,NaN,NaN,NaN,15.000000
13982,3351363,NaN,NaN,NaN,14.000000
13983,3352331,NaN,NaN,NaN,15.000000
13984,3353044,NaN,NaN,NaN,14.000000
13985,3353077,NaN,NaN,NaN,15.000000

In [14]:
full = full.merge(gcs, how="inner", left_on="PatientStayID", right_on="PatientStayID")
full

,PatientStayID,Class,Age,APACHEIVscore,APACHEIVaScore,UrgentAdmission,AdmissionCategory,NumBeds,TeachingStatus,Gender,...,mean_total protein,min_total protein,max_total protein,mean_WBC x 1000,min_WBC x 1000,max_WBC x 1000,mean_motor_GCS,mean_verbal_GCS,mean_eyes_GCS,mean_total_GCS
0,151708,1,79.0,38.0,38.0,0.0,4.0,4.0,1,Male,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13.933333
1,152171,1,84.0,38.0,38.0,1.0,4.0,2.0,0,Female,...,NaN,NaN,NaN,7.10,7.1,7.1,NaN,NaN,NaN,14.000000
2,155126,1,71.0,65.0,65.0,1.0,4.0,4.0,1,Male,...,NaN,NaN,NaN,13.10,13.1,13.1,NaN,NaN,NaN,11.333333
3,156970,1,56.0,32.0,32.0,0.0,4.0,4.0,1,Male,...,NaN,NaN,NaN,10.30,10.3,10.3,NaN,NaN,NaN,14.000000
4,165069,1,84.0,46.0,46.0,0.0,2.0,2.0,0,Male,...,NaN,NaN,NaN,7.80,7.8,7.8,NaN,NaN,NaN,15.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13981,3350678,0,60.0,52.0,52.0,0.0,4.0,4.0,0,Male,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.000000
13982,3351363,0,90.0,NaN,NaN,0.0,4.0,4.0,0,Female,...,NaN,NaN,NaN,3.80,3.8,3.8,NaN,NaN,NaN,14.000000
13983,3352331,0,75.0,48.0,48.0,0.0,4.0,2.0,0,Female,...,NaN,NaN,NaN,9.15,8.4,9.9,NaN,NaN,NaN,15.000000
13984,3353044,0,52.0,41.0,41.0,0.0,4.0,2.0,0,Male,...,NaN,NaN,NaN,10.20,10.2,10.2,NaN,NaN,NaN,14.000000
13985,3353077,0,60.0,36.0,36.0,0.0,4.0,4.0,0,Female,...,NaN,NaN,NaN,15.45,14.5,16.4,NaN,NaN,NaN,15.000000

In [15]:
full.to_csv("../csv/relative_{}hr_dataset_no_pts.csv".format(window), index = False)

12 hour version

In [63]:
full.to_csv("../csv/relative_{}hr_dataset_with_pts.csv".format(window), index = False)